name: enum_map_example
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  enum_map: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  enum_map_gen: ^0.2.0

dependency_overrides:
  enum_map: { path: ../ }
  enum_map_gen: { path: ../../enum_map_gen }
