builders:
  enum_map:
    import: 'package:enum_map_gen/builder.dart'
    builder_factories:
      - modifiableEnumMapBuilder
      - unmodifiableEnumMapBuilder
    build_extensions: {'.dart': ['enum_map_gen.g.part']}
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
